


[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "cqd"
version = "1.0.0"
description = "Time-Independent Schrödinger Equation (TISE) for a particle trapped in an Infinite Square Well"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "matplotlib",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.coverage.run]
omit = [
    "src/se/__init__.py",
] 